### PR TITLE
update code to use hooks

### PR DESCRIPTION
**Pull request by misaku**
update code to use hooks

### CODE REVIEW

**Comment by misaku** [comment]
i update but  I'm having trouble with two parts, and i can't resolve yet

**Comment by igor-nm** [comment]
Wich your problem ? If I can, I'll help you =D

**Comment by misaku** [comment]
sorry, I confused with another project what I went updated to hooks.
this submition is ok.
my problem was  in:[this link](https://github.com/benevbright/react-navigation-collapsible/issues/88)

**Comment by misaku** [comment]
but i think this code can be better i will refactory in this week and i try to  include useMemo.

**Comment by Relax594** [comment]
something broke the animation here. Items size stays like its the current selected once it got selected for the first time.

**Comment by peterpme** [comment]
Hi there,

We've taken over this repo as `expo-step-indicator` located here: https://github.com/draftbit/expo-step-indicator

Currently just trying to get this library up to date and then we can work on typescript support + hooks, etc.

Thanks!

**Pull request closed without merging**
