### PR TITLE
isNaN check

### PR DESCRIPTION
**Pull request by rf1804**
Bug resolved

### CODE REVIEW

**Comment by tomskopek** [comment]
👍 on this!
Resolves bug when `stepCount={1}`

**Comment by rf1804** [comment]
> 👍 on this!
> Resolves bug when `stepCount={1}`

But what if stepCount is not needed 1, default is already stepCount={5}
I believe long term solution would be isNan check

**Comment by tomskopek** [comment]
I don't really understand what you are saying @rf1804 

I'm saying that your solution helped me render the step-indicator when my stepCount prop was 1 (thanks!)

**Comment by rf1804** [comment]
@24ark

**Pull request closed without merging**
