### PR TITLE
Update StepIndicator.js

### PR DESCRIPTION
**Pull request by kpfefer**
Replace deprecated lifecycle method

### CODE REVIEW

**Comment by tadeumx1** [comment]
Hi @kpfefer so I see that your MR fix the [#78](`https://github.com/24ark/react-native-step-indicator/issues/78`) Warning componentWillReceiveProps is being deprecated, and I think your fix is gonna work, to the mainteners see your this, can you change the title to something like Correct Warning ComponentWillReceiveProps is being deprecated  ? I really want to see these changes accepted 😀 

@24ark accept this please

**Comment by annjawn** [comment]
@24ark Do you mind merging this please????

**Comment by MohdFaizan123** [comment]
@24ark Please merge this, we still getting this warning.

**Comment by FadiAboMsalam** [comment]
@24ark  are you still maintaining this repo ?

**Comment by Relax594** [comment]
"Reset" Animation is broken after this one. All steps will be shown as currently selected (height and width does not reset, background and bordercolor does somehow) after being selected once.

**Comment by annjawn** [comment]
@peterpme that is awesome news. I just did `npm install expo-step-indicator --save` and used it and the `componentWillReceiveProps` warning has now gone. Is it safe to continue using release `0.1.2`? Also, It would be great to update the installation instructions.

**Comment by peterpme** [comment]
Yes you can safely use 0.1.2 @annjawn thanks!

**Pull request closed without merging**
